### ISSUE TITLE
Missing project license information.

### ISSUE THREAD

**Issue by coderjoe** [Soleone/sc2ranks#2]
Hi,

I've recently started a fork of this project with the intent of adding some tests, functionality, and allowing it to be created into a gem.  

During this process I auto-generated a LICENSE file. I realized this morning it was probably incredibly presumptuous of me to do so since you're the original author and you haven't released your licensing terms.

Since you're the original source author you're the only one able to determine/allow new licenses.

The license I generated was a BSD Style license with no restrictions on use. If this is OK with you please let me know and I'll keep the licensing information around on my fork... otherwise let me know and I'll remove it/change it to whatever you see fit.

**Comment by Soleone** [comment]
Ah, thanks for the note! I have updated the master branch with a (MIT) license which should be free enough. Thanks for the forking action, be sure to let me know when your changes are ready to be merged in.

Cheers

**Comment by coderjoe** [comment]
Will do, thanks!
